'use server';
/**
 * @fileOverview A flow for generating creative prompts based on user input.
 *
 * - generateCreativePrompts - A function that generates creative prompts.
 * - GenerateCreativePromptsInput - The input type for the generateCreativePrompts function.
 * - GenerateCreativePromptsOutput - The return type for the generateCreativePrompts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCreativePromptsInputSchema = z.object({
  input: z.string().describe('User input to generate creative prompts from.'),
});
export type GenerateCreativePromptsInput = z.infer<
  typeof GenerateCreativePromptsInputSchema
>;

const GenerateCreativePromptsOutputSchema = z.object({
  prompt: z.string().describe('A creative prompt generated by the AI.'),
});
export type GenerateCreativePromptsOutput = z.infer<
  typeof GenerateCreativePromptsOutputSchema
>;

export async function generateCreativePrompts(
  input: GenerateCreativePromptsInput
): Promise<GenerateCreativePromptsOutput> {
  return generateCreativePromptsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCreativePromptsPrompt',
  input: {schema: GenerateCreativePromptsInputSchema},
  output: {schema: GenerateCreativePromptsOutputSchema},
  prompt: `You are a creative AI that helps users generate creative prompts.
  Based on the user input, generate a creative prompt that can be used to enhance their creative projects.

  User Input: {{{input}}}
  `,
});

const generateCreativePromptsFlow = ai.defineFlow(
  {
    name: 'generateCreativePromptsFlow',
    inputSchema: GenerateCreativePromptsInputSchema,
    outputSchema: GenerateCreativePromptsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
