// This file is automatically generated. Do not modify it manually.
'use client';
import { useEffect, useState, useMemo } from 'react';
import {
  collection,
  onSnapshot,
  Query,
  DocumentData,
  query,
  where,
  limit,
  orderBy,
  startAt,
  startAfter,
  endAt,
  endBefore,
  QueryConstraint,
} from 'firebase/firestore';

import { useFirestore } from '../provider';

type QueryOptions = {
  where?: [string, any, any];
  limit?: number;
  orderBy?: [string, 'asc' | 'desc'];
  startAt?: any[];
  startAfter?: any[];
  endAt?: any[];
  endBefore?: any[];
};

export function useCollection<T>(path: string, options?: QueryOptions) {
  const firestore = useFirestore();
  const [data, setData] = useState<T[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const queryConstraints: QueryConstraint[] = useMemo(() => {
    const constraints: QueryConstraint[] = [];
    if (options?.where) constraints.push(where(...options.where));
    if (options?.orderBy) constraints.push(orderBy(...options.orderBy));
    if (options?.startAt) constraints.push(startAt(...options.startAt));
    if (options?.startAfter)
      constraints.push(startAfter(...options.startAfter));
    if (options?.endAt) constraints.push(endAt(...options.endAt));
    if (options?.endBefore) constraints.push(endBefore(...options.endBefore));
    if (options?.limit) constraints.push(limit(options.limit));
    return constraints;
  }, [options]);

  useEffect(() => {
    if (!firestore) return;

    const collectionRef = collection(firestore, path);
    const q = query(collectionRef, ...queryConstraints);

    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {
        const docs = snapshot.docs.map(
          (doc) => ({ id: doc.id, ...doc.data() } as T)
        );
        setData(docs);
        setIsLoading(false);
      },
      (err) => {
        setError(err);
        setIsLoading(false);
      }
    );

    return () => unsubscribe();
  }, [firestore, path, queryConstraints]);

  return { data, isLoading, error };
}
